# Generated by Django 5.0.3 on 2024-03-26 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0003_cart_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
