# Generated by Django 5.0.3 on 2024-03-28 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_remove_product_thumbnail_order_orderitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='merchant_id',
            new_name='payment_intent',
        ),
    ]
